version: '3'
services:

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - /var/lib/mysql-test:/var/lib/mysql
      - ./mysql_init/:/docker-entrypoint-initdb.d/
    networks:
      - mysqldb
    restart: always
    ports:
      - "3305:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment:
      - PMA_HOST=mysql
    networks:
      - mysqldb
    ports:
      - "8022:80"
    depends_on:
      - mysql
    restart: always


networks:
  mysqldb:
    external:
      name: test-mysql
